### PR TITLE
Adds 51 games

### PR DESCRIPTION
**Pull request by gamebits**
Adds 51 games from my personal collection:

* A Fold Apart
* A Memoir Blue
* Bastion
* Blanc
* Boyfriend Dungeon
* Cursed Castilla
* Cyber Shadow
* Donut County
* Dungeons of Dreadrock
* ElecHead
* F-Zero 99
* FAR - Lone Sails
* FIGHTING EX LAYER ANOTHER DASH
* Firewatch
* Florence
* Horizon Chase Turbo
* It Takes Two
* Kathy Rain Director's Cut
* Lode Runner Legacy
* Lonely Mountains: Downhill
* Lumo
* Mark of the Ninja Remastered
* Need for Speed Hot Pursuit Remastered
* Nintendo Switch Sports - Demo
* Ocean's Heart
* Once Upon a Jester
* Pac-Man Championship Edition 2 Plus
* RPG Maker MV
* Scott Pilgrim vs. The World The Game
* Shadows of Adam
* Spiritfarer
* Super Arcade Racing
* Super Bomberman R Online
* Swords & Bones
* Tetris Effect
* The Oregon Trail
* The Red Lantern
* The Stanley Parable Ultra Deluxe
* Thomas Was Not Alone
* TowerFall
* Trash Quest
* Triangle Strategy - Demo
* TRON Identity
* Twelve Minutes
* Uno
* Venba
* Warlock of Firetop Mountai
* Warlock's Tower
* When the Past was Around
* Wide Ocean Big Jacket
* Wilmot's Warehouse

### CODE REVIEW

**Comment by gamebits** [comment]
@RenanGreca May I please get a review of this PR, or be granted write access to merge?

**Comment by RenanGreca** [comment]
Hi @gamebits thanks for the PR; I merge them when I can, sometimes it can take a while. :)

**Comment by gamebits** [comment]
Thank you! 🙏

**Comment by RenanGreca** [comment]
@gamebits Thanks a ton for the contributions to the repo! I saw you even resolved some issues. I think it's a good idea to grant you merge access. If you're still up for that let me know.

**Comment by gamebits** [comment]
@RenanGreca I'd be up for that! I've been working through my Switch backlog and will surely have more games to contribute.

Thanks! 😃

**Pull request merged**
